[project]
authors = ["ken <1610057945@qq.com>"]
channels = ["conda-forge"]
name = "segmentation"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"

[system-requirements]
cuda = "12"

[pypi-dependencies]
torch = ">=2.6.0, <3"
torchvision = ">=0.21.0, <0.22"
numpy = ">=2.2.4, <3"
pillow = ">=11.2.1, <12"
lightning = ">=2.5.1, <3"
tensorboard = ">=2.19.0, <3"
tensorboardx = ">=2.6.2.2, <3"
standard-imghdr = ">=3.13.0, <4"
wandb = ">=0.19.9, <0.20"
